name: recommender
description: An image based product recommender app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  camera: ^0.5.8+11
  path_provider: ^1.6.22
  path: ^1.7.0
  modal_bottom_sheet: ^0.2.2
  http: ^0.12.2
  url_launcher: ^5.7.8
  rflutter_alert: ^1.1.0
  animated_text_kit: ^2.5.1
  progress_indicators: ^0.1.5
  flutter_staggered_animations: ^0.1.2
  font_awesome_flutter: ^8.10.0
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: fonts/Itim-regular.ttf
    - family: Reem
      fonts:
        - asset: fonts/ReemKufi-Regular.ttf
    - family: SourceSans
      fonts:
        - asset: fonts/SourceSansPro.ttf